#!/bin/sh
# Generated by scripts/install-native-host.sh — do not edit by hand, it
# gets overwritten on every install.
#
# Firefox spawns native-messaging hosts with a minimal environment and
# no guarantee that PATH includes wherever `node` actually lives (e.g.
# Homebrew's /opt/homebrew/bin on Apple Silicon isn't on the default GUI
# app PATH). This wrapper hardcodes the exact node binary resolved at
# install time instead of relying on host.js's `#!/usr/bin/env node`
# shebang to find one at runtime.
exec "__NODE_PATH__" "__HOST_JS_PATH__" "$@"
