#!/bin/sh
# Generated by scripts/install-native-host*.sh — do not edit by hand, it
# gets overwritten on every install.
#
# Firefox/Chrome/Brave all spawn native-messaging hosts with a minimal
# environment and no guarantee that PATH includes wherever `node`
# actually lives (e.g. Homebrew's /opt/homebrew/bin on Apple Silicon
# isn't on the default GUI app PATH). This wrapper hardcodes the exact
# node binary resolved at install time instead of relying on host.js's
# `#!/usr/bin/env node` shebang to find one at runtime.
#
# "--source=__BROWSER_SOURCE__" goes first, ahead of whatever the
# browser itself appends as "$@" — it's how host.js tells which
# browser's heartbeat it's forwarding (see host.js's own comment).
# Each install script writes its own copy of this file under its own
# name (run-host-firefox.sh, run-host-chrome.sh, run-host-brave.sh) with
# its own browser name baked in, rather than all three sharing one
# generated file the way they used to.
exec "__NODE_PATH__" "__HOST_JS_PATH__" "--source=__BROWSER_SOURCE__" "$@"
