#!/usr/bin/env node
"use strict";
// Entrypoint. The browser (Firefox/Zen, Chrome, or Brave) spawns this
// process per native-messaging session and talks to it over
// stdin/stdout using the framing in
// src/stdio-framing.js. This file only wires stdio to the socket bridge
// — see CLAUDE.md: native-host is a thin, dumb pipe, no blocklist logic.

const { readMessages, writeMessage } = require("./src/stdio-framing");
const { SocketBridge } = require("./src/socket-bridge");
const SOCKET_PATH = require("./src/socket-path");

function log(...args) {
  // stdout is reserved for the native-messaging protocol; all
  // human-readable logs must go to stderr (visible via Console.app or
  // by running this script directly in a terminal).
  console.error("[native-host]", ...args);
}

// Firefox, Chrome, and Brave all spawn this exact same host.js, over
// the exact same message shape, into the exact same socket — nothing
// about the connection itself says which browser it came from. Each
// browser's own per-browser wrapper script (generated by
// scripts/install-native-host*.sh from
// manifest/run-host.template.sh) passes "--source=<name>" ahead of
// whatever args the browser itself appends, so the app can tell a live
// Chrome heartbeat apart from a dead Firefox one instead of treating
// every browser's heartbeat as interchangeable (see HeartbeatMonitor.swift
// and docs/HOW-IT-WORKS.md's heartbeat section). Not itself a decision
// about what to do with that information — still just labeling the pipe,
// not reading from it.
const source = (() => {
  const arg = process.argv.find((a) => a.startsWith("--source="));
  return arg ? arg.slice("--source=".length) : "unknown";
})();

const bridge = new SocketBridge(SOCKET_PATH, {
  onMessage: (message) => writeMessage(process.stdout, message),
  onLog: log,
});

bridge.connect();

readMessages(process.stdin, (message) => bridge.send({ ...message, source }));

process.stdin.on("end", () => {
  bridge.close();
  process.exit(0);
});

process.stdin.resume();
